name: 🔳 Verification serveur Dev

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: dev-server-check-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REMOTE_ENV : dev
  REMOTE_CHEMIN: ${{ secrets.REMOTE_CHEMIN }}
  ADRESSE_GLOBAL: ${{ vars.ADRESSE_GLOBAL }}
  ADRESSE_LOCAL: ${{ vars.ADRESSE_LOCAL }}

jobs:
  dev-check:
    name: Verification connexion & dossier serveur dev
    runs-on: ubuntu-latest

    steps:
      - name: Verifier les variables requises
        run: |
          miss=0
          for v in REMOTE_CHEMIN ADRESSE_GLOBAL ADRESSE_LOCAL; do
            if [ -z "${!v}" ]; then
              echo "::error title=Variable manquante::$v n'est pas défini."
              miss=1
            else
              echo "::notice title=Variable::$v=${!v}"
            fi
          done
          [ "$miss" -eq 0 ] || exit 1

      - name: Construire le chemin cible
        id: path
        shell: bash
        run: |
          REMOTE_PATH="${REMOTE_CHEMIN%/}/${ADRESSE_GLOBAL%/}/${REMOTE_ENV}/${ADRESSE_LOCAL#/}"
          echo "REMOTE_PATH=$REMOTE_PATH"
          echo "REMOTE_PATH=$REMOTE_PATH" >> "$GITHUB_OUTPUT"

      - name: Configurer SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verifier connexion SSH
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }} "echo 'Connexion SSH OK'"

      - name: Verifier/Creer le dossier distant
        run: |
          REMOTE_PATH="${{ steps.path.outputs.REMOTE_PATH }}"
          echo "Vérification du dossier : $REMOTE_PATH"
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }} "\
            if [ -d \"$REMOTE_PATH\" ]; then \
              echo '✅ Dossier déjà présent : $REMOTE_PATH'; \
            else \
              echo '⚠️ Dossier absent, création en cours : $REMOTE_PATH'; \
              mkdir -p \"$REMOTE_PATH\" && echo '✅ Dossier créé.'; \
            fi"
