# Exemple d'utilisation du workflow de suppression de branche après merge avec version
# Ce workflow supprime automatiquement la branche source après la fusion d'une PR

name: 🗑 Supprimer la branche après fusion

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

env:
  # Liste des branches à ne JAMAIS supprimer automatiquement (séparées par des virgules)
  FORBIDDEN_BRANCHES: develop,homol

jobs:
  delete-branch:
    uses: LeZouzouEnWeb/workflows/.github/workflows/delete-branch-after-merge.yml@v1.0.0
    permissions:
      contents: write
      pull-requests: write
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
