# Exemple d'utilisation du workflow de liaison de tickets avec version
# Ce workflow détecte et lie automatiquement les tickets/issues dans les PR

name: 🔗 Lier les tickets à la PR

on:
  pull_request:
    branches: [ develop ]
    types: [opened, edited, synchronize, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  link:
    uses: LeZouzouEnWeb/workflows/.github/workflows/link-issues-in-pr.yml@v1.0.0
    permissions:
      contents: read
      pull-requests: write
