# Exemple d'utilisation du workflow de mise à jour du titre de PR avec version
# Ce workflow normalise automatiquement le titre de la PR selon le nom de la branche

name: 🔄 Mettre à jour le titre de la PR

on:
  pull_request:
    branches: [ develop ]
    types: [opened, edited, synchronize, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-title:
    uses: LeZouzouEnWeb/workflows/.github/workflows/update-pr-title.yml@v1.0.0
    permissions:
      contents: read
      pull-requests: write
