# Exemple d'utilisation du workflow de vérification serveur HOMOL
# Ce workflow vérifie la connexion et l'existence du dossier sur le serveur HOMOL

name: 🔳 Vérification serveur HOMOL

on:
  pull_request:
    branches: [ homol ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: homol-server-check-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  homol-check:
    uses: LeZouzouEnWeb/workflows/.github/workflows/homol-server-check-pr.yml@main
    permissions:
      contents: read
    secrets:
      REMOTE_CHEMIN: ${{ secrets.REMOTE_CHEMIN }}
      SFTP_HOST: ${{ secrets.SFTP_HOST }}
      SFTP_USER: ${{ secrets.SFTP_USER }}
      SFTP_PORT: ${{ secrets.SFTP_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      ADRESSE_GLOBAL: ${{ vars.ADRESSE_GLOBAL }}
      ADRESSE_LOCAL: ${{ vars.ADRESSE_LOCAL }}
