# Exemple d'utilisation du workflow de vérification source PR - HOMOL
# Ce workflow s'assure que seules les PR de develop vers homol sont autorisées

name: 🔒 Vérification PR develop → homol

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - homol

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check-pr-source:
    uses: LeZouzouEnWeb/workflows/.github/workflows/check-pr-source.yml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write
    with:
      source_branch: develop
      target_branch: homol
