# Exemple d'utilisation du workflow de vérification PR vers PROD
# Ce workflow s'assure que seules les PR de homol vers main sont autorisées

name: 🔒 Vérification PR homol → main

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check-pr-source:
    name: 🔒 Vérification PR homol → Main
    uses: LeZouzouEnWeb/workflows/.github/workflows/check-pr-source.yml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write
    with:
      source_branch: homol
      target_branch: main
