# Exemple d'utilisation du workflow de vérification PR vers PROD
# Ce workflow s'assure que seules les PR de homol vers main sont autorisées

name: 🔒 Vérification PR homol → main

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  gate:
    uses: LeZouzouEnWeb/workflows/.github/workflows/prod-check-pr-depuis-homol.yml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write
