# Exemple d'utilisation du workflow de vérification serveur PROD
# Ce workflow vérifie la connexion et l'existence du dossier sur le serveur PROD

name: 🔳 Vérification serveur PROD

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: prod-server-check-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  prod-check:
    uses: LeZouzouEnWeb/workflows/.github/workflows/prod-server-check-pr.yml@main
    permissions:
      contents: read
    secrets:
      REMOTE_CHEMIN: ${{ secrets.REMOTE_CHEMIN }}
      SFTP_HOST: ${{ secrets.SFTP_HOST }}
      SFTP_USER: ${{ secrets.SFTP_USER }}
      SFTP_PORT: ${{ secrets.SFTP_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      ADRESSE_GLOBAL: ${{ vars.ADRESSE_GLOBAL }}
      ADRESSE_LOCAL: ${{ vars.ADRESSE_LOCAL }}
      remote_env: prod
      PATH_ORDER: local-env  # 'local-env' (défaut) ou 'env-local'
