name: use-delete-branch-after-merge.yml
on:
  workflow_dispatch:

jobs:
  call-shared:
    uses: LeZouzouEnWeb/corbidev-actions-central/.github/workflows/delete-branch-after-merge.yml@v1
    secrets: inherit
